# Generated by Django 4.2 on 2025-03-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
            ],
        ),
    ]
