# Generated by Django 4.2 on 2025-03-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0002_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='product',
            new_name='product_name',
        ),
    ]
