# Generated by Django 4.2 on 2025-03-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0003_rename_product_supplier_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateField(),
        ),
    ]
