# Generated by Django 4.2 on 2025-03-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0004_alter_stock_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='date_added',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='stock_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='price_per_item',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='supplier_name',
            new_name='stock',
        ),
    ]
