# Generated by Django 4.2 on 2025-03-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0005_rename_date_added_stock_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock',
            new_name='product',
        ),
    ]
