# Generated by Django 4.2 on 2025-03-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0006_rename_stock_stock_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='product_name',
            new_name='productname',
        ),
    ]
