# Generated by Django 4.2 on 2025-03-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0009_sale_alter_stock_date_delete_stockhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='buyingprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='autoapp.stock'),
        ),
    ]
