# Generated by Django 4.2 on 2025-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0015_alter_employeeprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('boss', 'Boss'), ('employee', 'Employee')], default='employee', max_length=10),
        ),
    ]
